### ISSUE TITLE
Improve handling of cases when image size is too small in to_fits_sip

### ISSUE THREAD

**Issue by mcara** [spacetelescope/gwcs#336]
The `to_fits_sip` crashes when bounding box of the WCS is smaller than the number of points to be used for fitting SIP - see https://github.com/spacetelescope/jwst/pull/5507#issuecomment-746615630 

I think the issue is that the code should allow sub-pixel steps: there is no fundamental reason forcing us to have integer steps.

I will make a PR for this.

**Comment by mcara** [comment]
CC: @jdavies-st @perrygreenfield

**Comment by perrygreenfield** [comment]
While it seems to make logical sense (from a robustness point of view), I can't see any practical need to do that. A different approach would just make the minimum step size 1.

**Comment by mcara** [comment]
Practical need is to use the minimum number of points that user requested. There is nothing special about evaluating WCS at fractional positions versus evaluating at integer positions: the accuracy of the forward transformation at fractional positions should be the same as at integer positions and so fitting a SIP polynomial should be just as successful.

**Comment by mcara** [comment]
Also, in the lines:

https://github.com/spacetelescope/gwcs/blob/45f65154ac57b8714aa46e2cf12b415bbcc3cd45/gwcs/wcs.py#L1435-L1436

computed `crpix` seems to be problematic if `xmin>>1`: then `crpix` could be outside the image. I think the correct formula should have `+` instead of `-`.

**Comment by perrygreenfield** [comment]
I understand, yet anyone that is relying on such subsampling of pixels for SIP fitting purposes is delusional. Perhaps I'm being too harsh. Misinformed. Or maybe I'm delusional :-)

**Comment by mcara** [comment]
Nothing wrong with fitting at fractional pixel values and there is nothing magical about integer pixel values. Even velocity aberration will make pixels look bigger/smaller (finer or coarser sampling) in the same scene at different times of the year :) I do not see an issue at all. Moreover, the purpose is to fit a polynomial to an analytical model and there is no mathematical, numerical, or computational reason (except when step becomes 1e-20 or so) not to do it. No one imagines that this would improve the quality of the distortion approximation used in the forward model, but if you do want to set minimum number of points to 32 (default value) then, as far as I can see there just a couple of options:

- allow subpixel sampling (best, IMO);
- set step to 1 and automatically reduce the number of fit points and issue a warning;
- raise an exception.

Last option seems to unnecessary (overkill) and the second option would result in lower accuracy of the _fit_ (not of the ideal distortion model).

**Comment by mcara** [comment]
Or set default value for the number of points to 2.

**Comment by perrygreenfield** [comment]
I will go with @mcara 's judgement.

**Comment by jdavies-st** [comment]
I agree with @mcara.  There's not a strong reason to think one needs fewer points in a 64x64 array compared to a 2048x2048 array unless one knows something about the distortion, i.e. it is less bumpy on small scales than on large scales.  I.e. there's no reason to think that the 64x64 array could have have a distortion that requires many of those points to be fit.

As it is now, for small arrays of 200x200 are only fit with several points, which only fits a CD matrix because the sampling is sparse, though it might be better to fit with a 2nd order SIP, for instance.  One doesn't know unless one samples more pixels.

One way to do this is to make the fit always use a grid of 32x32 or 64x64 points, and find the subpixel step that makes that work.  `gwcs.wcstools.grid_from_bounding_box` would be useful for generating the grid once you know the step size.

I assume one wants to limit the number of points used for the fit because as the number of points goes up, the compute resources goes up?

Put another way, for 63x63 subarray (or a 31x31 subarray), I don't think the SIP fit is very meaningful if you're just fitting to 2 or 3 sampled pixesl in each dimension.  In practice for these cases, you just get a CD matrix back with no higher order terms.
