### ISSUE TITLE
Consider adding a description in the docs about manifest changes in #469

### ISSUE THREAD

**Issue by braingram** [spacetelescope/gwcs#473]
As brought up in this comment:
https://github.com/spacetelescope/jdaviz/issues/2446#issuecomment-1716413809

Users opening files generated with gwcs prior to the fix included in #469 will see warnings like the following:
```
asdf.exceptions.AsdfWarning: File was created with extension URI 'asdf://asdf-format.org/astronomy/gwcs/extensions/gwcs-1.0.0' (from package gwcs==0.18.2), which is not currently installed 
```
Due to `1.0.0` no longer being registered as an extension. As `1.0.1` and `1.1.0` cover all tags from `1.0.0` it is safe to ignore this warning but this nuance will likely be unknown to gwcs users.

One option would be to update the documentation and release notes describing the issue and can be ignored until the file can e regenerate (which will get rid of the warning).

I'm also open to suggestions on other ways to handle this (including possibly registering a 'dummy' `1.0.0` extension which does nothing yet should hide the warning). @nden @eslavich do you think this is worth investigating as an option?

**Comment by nden** [comment]
I'm not sure we need to go as far as adding a dummy extension. These files will be regenerated soon and while there probably will be many old files lying around, the pipeline issues a ton of other benign warnings. We can clarify this in the documentation but more importantly we should make a release so that this code is used by the next reprocessing run.
